name: Test Runner
on:
  push:
    branches: ["main"]

jobs:
  test-sur-ma-machine:
    runs-on: self-hosted  # <--- Indique d'utiliser ta machine Debian
    steps:
      - name: Verification
        run: |
          echo "Salut GitHub, ici ta machine Debian !"
          echo "Nom de la machine :"
          hostname
          echo "Utilisateur actuel :"
          whoami
          echo "OS en cours :"
          uname -a
